---
- name: Install package
  become: True
  package:
    name: kubernetes-hyperkube-kubelet
    state: present

- name: Create static pod directory
  file:
    name: "{{ kubelet_static_pod_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure package
  become: True
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: systemd.service.j2
      dest: /etc/systemd/system/kubelet.service
    - src: kubelet.conf.j2
      dest: /etc/kubernetes/kubelet/config.conf
  notify:
    - Reload systemd
    - Restart kubelet

- name: Start service
  service:
    name: kubelet
    state: started
    enabled: True
